name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...
      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:latest .
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Push image
        run: |
          docker tag ${{ github.repository }}:latest ${{ secrets.DOCKERHUB_USER }}/set-cloudflare-dns:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/set-cloudflare-dns:latest
